# Certificate paths:
ovirt_libvirt_default_trust_store: '/etc/pki/libvirt'
ovirt_vdsm_trust_store: '/etc/pki/vdsm'

# Certificate files (relative to certificate paths):
ovirt_vdsm_cert_file: 'certs/vdsmcert.pem'
ovirt_qemu_cert_file: 'libvirt-migrate/server-cert.pem'
ovirt_qemu_client_cert_file: 'libvirt-migrate/client-cert.pem'
ovirt_vdsm_spice_cert_file: 'libvirt-spice/server-cert.pem'
ovirt_libvirt_default_client_cert_file: 'clientcert.pem'

# Certificate keys (relative to certificate paths):
ovirt_vdsm_key_file: 'keys/vdsmkey.pem'
ovirt_qemu_key_file: 'libvirt-migrate/server-key.pem'
ovirt_qemu_client_key_file: 'libvirt-migrate/client-key.pem'
ovirt_vdsm_spice_key_file: 'libvirt-spice/server-key.pem'
ovirt_libvirt_default_client_key_file: 'private/clientkey.pem'
ovirt_vdsm_key_pending_file: 'keys/vdsmkey.pending.pem'
ovirt_qemu_key_pending_file: 'libvirt-migrate/server-key.pending.pem'

# CA files (relative to certificate paths):
ovirt_vdsm_spice_ca_file: 'libvirt-spice/ca-cert.pem'
ovirt_libvirt_default_client_ca_file: '../CA/cacert.pem'
ovirt_vdsm_ca_file: 'certs/cacert.pem'
ovirt_qemu_ca_file: 'libvirt-migrate/ca-cert.pem'

# VDSM private key variables:
ovirt_vdsm_key_size: 2048
ovirt_vdsm_key_type: rsa
