---
dist: focal
language: java
jdk:
  - openjdk11
services:
  - postgresql
install: true
before_script:
  - psql -c "CREATE USER engine_test WITH PASSWORD 'test';" -U postgres
  - psql -d template1 -c "CREATE DATABASE engine_dao_tests OWNER engine_test;" -U postgres
  - psql -d engine_dao_tests -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";" -U postgres
  - sudo rm -rf /etc/securetty  # Work around ServletUtilsTest test
script:
  - "PGPASSWORD=\"test\" ./packaging/dbscripts/schema.sh -d engine_dao_tests -u engine_test -s localhost -p 5433 -c apply"
  - rm -rvf /home/travis/.m2/repository/
  - for i in `seq 1 120`; do sleep 60; echo 'keep alive'; done & mvn --quiet clean org.jacoco:jacoco-maven-plugin:prepare-agent install -P enable-dao-tests sonar:sonar -Dsonar.organization=default -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dengine.db.username=engine_test -Dengine.db.password=test -Dengine.db.url=jdbc:postgresql://localhost:5433/engine_dao_tests
env:
  global:
    - secure: kgBwT3IHk1vg1PHD4KKqkIOFlv4MGkOA+IK+nsTbPRJEvWpzZSgpHLuL+/2YuB4tntNMMj3LHwPTSJmaGLRdxaSjjv0MfzQA/fudLqTJ+FL3MuA++YcLSfjj6wj1dlMRj+0vYgCQcBMKTktDhGMdE6gUh42AQBzywqe1IcnX5Qs=
    - PGVER=12
    - PGPORT=5433
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-contrib-12
cache:
  directories:
    - $HOME/.m2
  before_cache:
    - rm -rf $HOME/.m2/repository/org/ovirt/
branches:
  only:
    - master
