---
- name: Detect host operating system
  set_fact:
    el_ver: "{{ ansible_distribution_major_version|int
        if ansible_distribution_file_variety == 'RedHat'
        else 0 }}"
    fc_ver: "{{ ansible_distribution_major_version|int
        if ansible_distribution == 'Fedora'
        else 0 }}"

- name: Fetch installed packages
  package_facts:
    manager: auto

- name: Check if vdsm is preinstalled
  set_fact:
    vdsm_preinstalled: "{{ 'vdsm' in ansible_facts.packages }}"

- name: Parse operating system release
  lineinfile:
    path: /etc/os-release
    line: 'VARIANT_ID="ovirt-node"'
  check_mode: yes
  register: node_presence

- name: Detect if host is a prebuilt image
  set_fact:
    node_host: "{{ not node_presence.changed }}"
