---
# We need to install ovirt-hosted-engine-setup first due to its dependency
# on specific ansible version to prevent collision with newer ansible versions
# on EL7, because yum on EL7 doesn't contain --nobest option
# We need to skip on non x86_64 architecture, because HE is not supported there
- name: Install ovirt-hosted-engine-setup package
  yum:
    name: ovirt-hosted-engine-setup
    state: present
  when: ansible_architecture == 'x86_64'
  tags:
    - skip_ansible_lint # E403

- name: Install ovirt-host package
  yum:
    name: ovirt-host
    state: present
  tags:
    - skip_ansible_lint # E403

- name: Get packages
  package_facts:
    manager: auto

- name: Verify minimum vdsm version exists
  fail:
    msg: "Minimum version required for vdsm is {{ host_deploy_vdsm_min_version }}"
  when: host_deploy_vdsm_min_version|float < ansible_facts.packages['vdsm'][0].version|float
